#!/usr/bin/env node
/**
 * pr-fix.mjs
 *
 * Fetches inline AI review comments from a PR and applies fixes using aider
 * pointed at Azure OpenAI. Designed to run inside the pr-fix.yml workflow.
 *
 * Flow:
 *  1. Fetch review comments from github-actions[bot] for the reviewed SHA
 *  2. Build a structured fix prompt
 *  3. Collect the unique files mentioned in comments (must exist on disk)
 *  4. Invoke aider via spawn() (no shell interpolation)
 *  5. If aider produced changes, commit with [ai-fix source=<sha>] marker and push
 */

import { spawnSync } from "child_process";
import { existsSync } from "fs";

const MAX_COMMENTS = 20;
const MAX_FILES = 15;

// ── env ──────────────────────────────────────────────────────────────────────

function getEnv(name, fallback = "") {
  return process.env[name]?.trim() || fallback;
}

function requireEnv(name) {
  const v = getEnv(name);
  if (!v) throw new Error(`Missing required env: ${name}`);
  return v;
}

const GH_TOKEN = requireEnv("GH_TOKEN");
const GH_API_URL = requireEnv("GH_API_URL");
const REPO = requireEnv("REPO");
const PR_NUMBER = requireEnv("PR_NUMBER");
const HEAD_SHA = requireEnv("HEAD_SHA");
const AZURE_DEPLOYMENT = getEnv("AZURE_OPENAI_DEPLOYMENT", "gpt-5.4");

// ── GitHub API helpers ────────────────────────────────────────────────────────

async function ghGet(path) {
  const res = await fetch(`${GH_API_URL.replace(/\/$/, "")}${path}`, {
    headers: {
      Authorization: `token ${GH_TOKEN}`,
      Accept: "application/vnd.github+json",
    },
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitHub API ${res.status} for ${path}: ${text}`);
  }
  return res.json();
}

// ── fetch review comments ─────────────────────────────────────────────────────

async function fetchBotReviewComments() {
  // Get all reviews on this PR, find the most recent one from github-actions[bot]
  // that was submitted against our HEAD_SHA.
  const reviews = await ghGet(`/repos/${REPO}/pulls/${PR_NUMBER}/reviews?per_page=100`);

  const botReview = reviews
    .filter(
      (r) =>
        r.user?.login === "github-actions[bot]" &&
        r.commit_id === HEAD_SHA
    )
    .sort((a, b) => b.id - a.id)[0]; // most recent

  if (!botReview) {
    console.log(
      `No AI review found for commit ${HEAD_SHA} on PR #${PR_NUMBER}. Nothing to fix.`
    );
    return [];
  }

  console.log(`Found AI review #${botReview.id} for commit ${HEAD_SHA}`);

  // Fetch inline comments for this PR and filter to those belonging to this review
  const allComments = await ghGet(
    `/repos/${REPO}/pulls/${PR_NUMBER}/comments?per_page=100`
  );

  const reviewComments = allComments.filter(
    (c) =>
      c.pull_request_review_id === botReview.id &&
      c.user?.login === "github-actions[bot]"
  );

  console.log(
    `Found ${reviewComments.length} inline comment(s) from AI review #${botReview.id}`
  );

  return reviewComments.slice(0, MAX_COMMENTS);
}

// ── build aider prompt ────────────────────────────────────────────────────────

function buildPrompt(comments) {
  const items = comments
    .map((c, i) => {
      const loc = c.path ? `${c.path}${c.line ? `:${c.line}` : ""}` : "general";
      return `${i + 1}. [${loc}]\n${c.body.replace(/^_Generated by.*$/m, "").trim()}`;
    })
    .join("\n\n");

  return `You are fixing issues identified in a pull request code review.
Apply ALL of the following fixes to the relevant files. Make targeted, minimal changes — do not refactor unrelated code.

Issues to fix:
${items}

After applying the fixes, ensure the code is consistent and compiles without errors.`;
}

// ── collect files ─────────────────────────────────────────────────────────────

function collectFiles(comments) {
  const seen = new Set();
  const files = [];

  for (const c of comments) {
    if (c.path && !seen.has(c.path)) {
      seen.add(c.path);
      // Only include files that actually exist on disk (guard against stale comments)
      if (existsSync(c.path)) {
        files.push(c.path);
      } else {
        console.warn(`Skipping comment on non-existent file: ${c.path}`);
      }
      if (files.length >= MAX_FILES) break;
    }
  }

  return files;
}

// ── run aider ─────────────────────────────────────────────────────────────────

function runAider(prompt, files) {
  const args = [
    "--model",
    `azure/${AZURE_DEPLOYMENT}`,
    "--yes",
    "--no-check-update",
    "--no-git",           // we manage git ourselves for a clean commit message
    "--message",
    prompt,
    ...files,
  ];

  console.log(`\nRunning aider on ${files.length} file(s): ${files.join(", ")}`);

  const result = spawnSync("aider", args, {
    stdio: "inherit",
    env: {
      ...process.env,
      // Ensure aider picks up Azure creds (LiteLLM env var names)
      AZURE_API_KEY: getEnv("AZURE_API_KEY"),
      AZURE_API_BASE: getEnv("AZURE_API_BASE"),
      AZURE_API_VERSION: getEnv("AZURE_API_VERSION"),
    },
  });

  if (result.error) {
    throw new Error(`Failed to spawn aider: ${result.error.message}`);
  }

  console.log(`\naider exited with code ${result.status}`);
  return result.status === 0;
}

// ── git helpers ───────────────────────────────────────────────────────────────

function git(...args) {
  const result = spawnSync("git", args, { stdio: "inherit" });
  if (result.error) throw new Error(`git ${args[0]} failed: ${result.error.message}`);
  return result.status === 0;
}

function hasChanges() {
  const result = spawnSync("git", ["diff", "--quiet"], { stdio: "inherit" });
  return result.status !== 0; // non-zero means there are changes
}

function commitAndPush() {
  // Include the source SHA so the deduplication step in the workflow
  // can detect this exact fix was already applied.
  const message = `fix: apply AI review suggestions [ai-fix source=${HEAD_SHA}]`;
  git("add", "-A");
  git("commit", "-m", message);
  git("push");
  console.log(`\nPushed fix commit for reviewed SHA ${HEAD_SHA}`);
}

// ── main ──────────────────────────────────────────────────────────────────────

async function main() {
  const comments = await fetchBotReviewComments();

  if (comments.length === 0) {
    console.log("No actionable comments found. Exiting cleanly.");
    process.exit(0);
  }

  const files = collectFiles(comments);

  if (files.length === 0) {
    console.log("No valid on-disk files referenced in comments. Exiting cleanly.");
    process.exit(0);
  }

  const prompt = buildPrompt(comments);
  const success = runAider(prompt, files);

  if (!success) {
    console.error("aider exited with a non-zero status. Skipping commit.");
    process.exit(1);
  }

  if (!hasChanges()) {
    console.log("aider made no changes. Nothing to commit.");
    process.exit(0);
  }

  commitAndPush();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
